package de.uulm.se.couchedit.processing.common.repository

/**
 * Interface for a ModelRepository where the contents need to be generated by the [recalculate] function before
 * they can be correctly accessed.
 *
 * TODO: Replace this with a changed flag mechanism or similar?
 */
interface CalculatedModelRepository: ModelRepositoryRead {
    fun recalculate()
}
